-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 23:15:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Donadeu_database_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Donadeu_database_v2
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Donadeu_database_v2` DEFAULT CHARACTER SET utf8 ;
USE `Donadeu_database_v2` ;

-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idAlmacen`),
  CONSTRAINT `fk_Almacen_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Donadeu_database_v2`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `Id_SistemaGestion` INT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  CONSTRAINT `fk_Clientes_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Donadeu_database_v2`.`Direccion` (`idDireccion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(45) NOT NULL,
  `latitud` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idDireccion`));



-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`DistanceBase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`DistanceBase` (
  `idDistanceBase` INT NOT NULL AUTO_INCREMENT,
  `tiempoViaje` FLOAT NULL,
  `tipoViaje` VARCHAR(45) NOT NULL,
  `distanciaViaje` FLOAT NULL,
  `Almacen_idAlmacen` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idDistanceBase`),
  CONSTRAINT `fk_DistanceBase_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `Donadeu_database_v2`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DistanceBase_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `Donadeu_database_v2`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`DistanceClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`DistanceClient` (
  `idDistanceClient` INT NOT NULL AUTO_INCREMENT,
  `tiempoViaje` FLOAT NULL,
  `distanciaViaje` FLOAT NULL,
  `Clientes_idClientes_origen` INT NOT NULL,
  `Clientes_idClientes_destino` INT NOT NULL,
  PRIMARY KEY (`idDistanceClient`),
  CONSTRAINT `fk_DistanceClient_Clientes1`
    FOREIGN KEY (`Clientes_idClientes_origen`)
    REFERENCES `Donadeu_database_v2`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DistanceClient_Clientes2`
    FOREIGN KEY (`Clientes_idClientes_destino`)
    REFERENCES `Donadeu_database_v2`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Itinerario` (
  `idItinerario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NOT NULL,
  `TiempoTotal` FLOAT NOT NULL,
  `DistanciaTotal` FLOAT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Vehiculos_idVehiculos` INT NOT NULL,
  `Almacen_idAlmacen` INT NOT NULL,
  PRIMARY KEY (`idItinerario`),
  CONSTRAINT `fk_Itinerario_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Donadeu_database_v2`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itinerario_Vehiculos1`
    FOREIGN KEY (`Vehiculos_idVehiculos`)
    REFERENCES `Donadeu_database_v2`.`Vehiculos` (`idVehiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itinerario_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `Donadeu_database_v2`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


ALTER TABLE Itinerario
  ADD turno VARCHAR(45) NOT NULL;

-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Secuenciamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Secuenciamiento` (
  `idSecuenciamiento` INT NOT NULL AUTO_INCREMENT,
  `orden` INT NULL,
  `DistanceClient_idDistanceClient` INT NULL,
  `DistanceBase_idDistanceBase` INT NULL,
  `Itinerario_idItinerario` INT NOT NULL,
  PRIMARY KEY (`idSecuenciamiento`),
  CONSTRAINT `fk_Secuenciamiento_DistanceClient`
    FOREIGN KEY (`DistanceClient_idDistanceClient`)
    REFERENCES `Donadeu_database_v2`.`DistanceClient` (`idDistanceClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Secuenciamiento_DistanceBase1`
    FOREIGN KEY (`DistanceBase_idDistanceBase`)
    REFERENCES `Donadeu_database_v2`.`DistanceBase` (`idDistanceBase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Secuenciamiento_Itinerario1`
    FOREIGN KEY (`Itinerario_idItinerario`)
    REFERENCES `Donadeu_database_v2`.`Itinerario` (`idItinerario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(100) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`));



-- -----------------------------------------------------
-- Table `Donadeu_database_v2`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donadeu_database_v2`.`Vehiculos` (
  `idVehiculos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `patente` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `capacidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idVehiculos`));



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
